POST http://127.0.0.1:8000/api/v1/auth/register
Accept: application/json
Content-Type:application/json

{
    "name": "admin",
    "email":  "admin@mail.com",
    "password": "vla54321",
    "c_password": "vla54321"
}

### login

POST http://127.0.0.1:8000/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
    "email":"vladyco@mail.com",
    "password": "vla54321"
}

### perfil

GET http://127.0.0.1:8000/api/user
Accept: application/json
Content-Type: application/json
Authorization: Bearer 3|fsgEb5Lkhb7vj0q6wwysKyWUyk71kcAI0Mynfytp

### perfil 2
GET http://127.0.0.1:8000/api/v1/auth/perfil
Accept: application/json
Content-Type: application/json
Authorization: Bearer 3|fsgEb5Lkhb7vj0q6wwysKyWUyk71kcAI0Mynfytp

### logout
POST http://127.0.0.1:8000/api/v1/auth/logout
Accept: application/json
Content-Type: application/json
Authorization: Bearer 3|fsgEb5Lkhb7vj0q6wwysKyWUyk71kcAI0Mynfytp
